### ISSUE TITLE
Driver is unusable for some people

### ISSUE THREAD

**Issue by InsaneGrox** [InsaneGrox/driver_kinectV2_neosVR#1]
Reported by alex derpy avali 🐦#1470 via discord DMs
Driver seems to be unusable for some people for unknown reasons, Correlation seems to be with some Visual studio redistributables versions, or AMD processors, I'm not certain however.

**Comment by tealsummernights** [comment]
I think this must be the issue I’m having. The program fails to detect the Kinect, though other programs can see it fine. I have an AMD CPU as well, for what it’s worth. I don’t know about the Visual Studio thing.

**Comment by alexderpyfox** [comment]
> I think this must be the issue I’m having. The program fails to detect the Kinect, though other programs can see it fine. I have an AMD CPU as well, for what it’s worth. I don’t know about the Visual Studio thing.

Have you tried the Kinect configuration verifier to see if it's running at stable 30fps?

**Comment by tealsummernights** [comment]
> Have you tried the Kinect configuration verifier to see if it's running at stable 30fps?

Yeah, the verifier checks out.

**Comment by InsaneGrox** [comment]
Closing this and archiving the whole repository because Sdraw added official support for all 8 trackers to the original driver
https://github.com/SDraw/driver_kinectV2 (Ability to enable trackers for specific bones)
